server:
  port: 9088
  servlet:
    context-path: /notification

app:
  services:
    getIdClient:
      url: http://localhost:9087/client/managment/getIdClient?email={email}

spring:
  application:
    name: notification
  datasource:
    url: jdbc:mysql://localhost:3306/gescom_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 465
    username: mbomapatjean@gmail.com
    password: sbcaauqfqblqcuxg
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
